name: MSBuild

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/actions/**'
      - 'README.md'
      - 'README.*'
      - '.gitignore'
      - '.gitattributes'
      - '.github/**'
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: false
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Release Build
      uses: ./.github/workflows/release-build.yml
      with:
        bump: ${{ github.event.inputs.bump }}
